# Generated by Django 3.2.13 on 2022-05-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
                'db_table': 'servers',
            },
        ),
    ]
